"""
SOC Audit Log Exporter & Executive Security Reporting Engine for NetGuard.

Exports security events, packet anomaly logs, and phishing scans into JSON,
CSV, and structured Markdown audit reports.
"""

import csv
import io
import json
from datetime import datetime, timezone
from netguard.core.db import get_session
from netguard.core.models import Event, PacketLog, PhishingScan, FirewallRule, FirewallDecision


def export_events_json(source: str = None, severity: str = None, limit: int = 500) -> str:
    """
    Export security events as a formatted JSON string.
    """
    with get_session() as session:
        query = session.query(Event)
        if source:
            query = query.filter_by(source=source)
        if severity:
            query = query.filter_by(severity=severity)
            
        events = query.order_by(Event.id.desc()).limit(limit).all()
        data = [e.to_dict() for e in events]
        return json.dumps(data, indent=2)


def export_events_csv(source: str = None, severity: str = None, limit: int = 500) -> str:
    """
    Export security events as a CSV string.
    """
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["ID", "Timestamp", "Source", "Severity", "Summary", "Raw Data"])

    with get_session() as session:
        query = session.query(Event)
        if source:
            query = query.filter_by(source=source)
        if severity:
            query = query.filter_by(severity=severity)
            
        events = query.order_by(Event.id.desc()).limit(limit).all()
        for e in events:
            writer.writerow([
                e.id,
                e.timestamp.isoformat() if e.timestamp else "",
                e.source,
                e.severity,
                e.summary,
                json.dumps(e.raw_data) if e.raw_data else ""
            ])

    return output.getvalue()


def generate_markdown_audit_report() -> str:
    """
    Generate an executive Markdown security audit report summarizing recent SOC activity.
    """
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    with get_session() as session:
        total_events = session.query(Event).count()
        critical_count = session.query(Event).filter_by(severity="critical").count()
        warning_count = session.query(Event).filter_by(severity="warning").count()
        info_count = session.query(Event).filter_by(severity="info").count()

        total_scans = session.query(PhishingScan).count()
        phishing_detected = session.query(PhishingScan).filter_by(verdict="phishing").count()
        suspicious_scans = session.query(PhishingScan).filter_by(verdict="suspicious").count()

        firewall_rule_count = session.query(FirewallRule).count()
        total_decisions = session.query(FirewallDecision).count()
        denied_decisions = session.query(FirewallDecision).filter_by(action_taken="deny").count()

        recent_threats = session.query(Event).filter(Event.severity.in_(["critical", "warning"])).order_by(Event.id.desc()).limit(5).all()

    report = []
    report.append("# 🛡️ NetGuard Executive Security Audit Report")
    report.append(f"**Generated:** {now_str}\n")
    report.append("---")
    report.append("## 📊 Incident Overview & SOC Metrics\n")
    report.append(f"- **Total Logged Security Events:** {total_events}")
    report.append(f"  - 🔴 **Critical Alerts:** {critical_count}")
    report.append(f"  - 🟡 **Warning Alerts:** {warning_count}")
    report.append(f"  - 🟢 **Info Logs:** {info_count}")
    report.append(f"- **Phishing Scans Conducted:** {total_scans} (Phishing Flagged: {phishing_detected}, Suspicious: {suspicious_scans})")
    report.append(f"- **Active Firewall Rules:** {firewall_rule_count}")
    report.append(f"- **Firewall Packet Decisions:** {total_decisions} (Denied Packets: {denied_decisions})\n")

    report.append("---")
    report.append("## 🚨 Top Recent Threat Alerts\n")

    if recent_threats:
        report.append("| ID | Severity | Source | Summary | Timestamp |")
        report.append("|---|---|---|---|---|")
        for t in recent_threats:
            sev_icon = "🔴" if t.severity == "critical" else "🟡"
            report.append(f"| {t.id} | {sev_icon} {t.severity.upper()} | {t.source} | {t.summary} | {t.timestamp.strftime('%Y-%m-%d %H:%M:%S')} |")
    else:
        report.append("_No critical or warning threat alerts recorded._")

    report.append("\n---")
    report.append("\n*Report automatically generated by NetGuard Threat Intelligence Engine.*")

    return "\n".join(report)
